version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8005:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    environment:
      APACHE_RUN_PORT: 8005

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: examen-totalpat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
