version: "3.8"

services:
  app:
    container_name: laravel_app     
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:80"                      
    volumes:
      - .:/var/www/html                
    depends_on:
      - mysql                        
    networks:
      - examen-red

  mysql:
    container_name: laravel_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: examen-totalpat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"                     
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - examen-red

volumes:
  mysql_data:

networks:
  examen-red:
    external: true                     
